apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-db
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: petclinic
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: demo-db
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-from-app
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: demo-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: petclinic
    ports:
    - protocol: TCP
      port: 5432
