apiVersion: v1
kind: Secret
metadata:
  name: demo-db
  namespace: petclinic
type: Opaque
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "demo-db"
  port: "5432"
  database: "petclinic"
  username: "petclinic"
  password: "admin123!"