apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic-sa
  namespace: petclinic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: petclinic-reader
  namespace: petclinic
rules:
- apiGroups: [""]
  resources: ["pods","services","endpoints","configmaps"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: petclinic-reader-binding
  namespace: petclinic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: petclinic-reader
subjects:
- kind: ServiceAccount
  name: petclinic-sa
  namespace: petclinic
